### PR TITLE
[#617] Indicate that all source clusters/datastores/networks have been mapped

### LINKED ISSUE #617: Indicate that all source clusters/datastores/networks have been mapped
Currently, after all source clusters/datastores/networks have been mapped, the source listbox is empty with no indication of why.  Some users have perceived this as a bug, particularly when navigating back and forth through the wizard.

We should indicate to the user that the listbox is empty due to all source clusters/datastores/networks having been mapped.

Note that this is different than the case described by #611 where the empty listbox is due to no clusters being returned by the server.

# Screens

## Empty listbox after mapping all source clusters
manageiq__migration

### PR DESCRIPTION
**Pull request by mturley**
Closes #617.

screenshot 2018-10-10 13 36 57

screenshot 2018-10-10 13 41 13

screenshot 2018-10-10 13 37 58

### CODE REVIEW

**Comment by vconzola** [comment]
@mturley Here's what the message should look like for clusters: 
4aa-createmapping-clusters

Similar messages should be included when source datastore and network lists are empty.

**Comment by mturley** [comment]
Thanks @vconzola. Updated the PR with screenshots.

**Comment by vconzola** [comment]
Well, that was quick. :-)

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 9eb7f989f4ecc696bfe4d409cc6b56859432e577
Author: Michael Ro <mikerodev@gmail.com>
Date:   Thu Oct 11 12:54:21 2018 -0400

    Merge pull request #703 from mturley/617-indicate-all-mapped
    
    [#617] Indicate that all source clusters/datastores/networks have been mapped
    
    (cherry picked from commit 11dd4e3a17b81d0927be4d33693ed78bfd22d2f1)
```

**Pull request merged**
