### PR TITLE
Fix tests we missed in PR #897

### PR DESCRIPTION
**Pull request by mturley**
I didn't realize that there were snapshot test failures when I merged #897... Travis CI failed to run on that PR! I should have noticed the lack of a green checkmark there.

I'll investigate what's going on with Travis, but master is broken right now, @mzazrivec can you merge this one for me when you get a chance?

### CODE REVIEW

**Comment by mturley** [comment]
We'll need to put the same BZ on this one that we do for #897, for the throttling changes, which I can't find at the moment.

**Comment by mturley** [comment]
I'm actually going to go ahead and self-merge this so we don't leave master in the red overnight.

**Comment by mturley** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1688951

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 396d010a7826f42ed338b288dedb8291cf312edc
Author: Mike Turley <mike.turley@alum.cs.umass.edu>
Date:   Tue Mar 12 17:47:31 2019 -0400

    Merge pull request #905 from mturley/fix-bad-snapshots
    
    Fix tests we missed in PR #897
    
    (cherry picked from commit d462568426622038f4835a68f8e02f9ed1b70067)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1693746
```

**Pull request merged**
