### PR TITLE
[Changelog] Update for Hammer-7

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label hammer/yes

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@mturley as time permits, can you review/merge.

**Comment by simaishi** [comment]
@JPrause I think this has `hammer-6` and `hammer-7` combined.

**Comment by JPrause** [comment]
Ugh! I see what I did. Thanks @simaishi and I'll fix that now.

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit e5faf042040ce34a882640c814f2b46ae66ead16
Author: Mike Turley <mturley@redhat.com>
Date:   Mon Jun 10 09:37:55 2019 -0400

    Merge pull request #979 from JPrause/hammer7_cl
    
    [Changelog] Update for Hammer-7
    
    (cherry picked from commit dee451301c946dccc5c407f8687e60998f1e4986)
```

**Pull request merged**
