### PR TITLE
[Changelog] Update for Hammer-10

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label hammer/yes

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 50ade0f73d7aefeed2c1ce82ca57c15d4b2c4f6c
Author: Adam Grare <agrare@redhat.com>
Date:   Fri Aug 9 12:03:55 2019 -0400

    Merge pull request #1018 from JPrause/hammer10_cl
    
    [Changelog] Update for Hammer-10
    
    (cherry picked from commit 81cce645157be4dff1739a2bd14d610e36f678c4)
```

**Comment by simaishi** [comment]
@JPrause In this PR, https://github.com/ManageIQ/manageiq-v2v/pull/1007 was moved from `ivanchuk-1-beta2` to `hammer-10` section and I think we need to avoid doing that (move a PR from a branch to another branch). It looks ok in `master` branch, but this will cause the PR to "disappear" from ivanchuk changelog because we don't keep hammer changelog in ivanchuk branch.

Noticed it because backporting https://github.com/ManageIQ/manageiq-v2v/pull/1028 conflicted.

**Comment by JPrause** [comment]
@simaishi got it. Understood. Thanks for the heads-up.

**Comment by simaishi** [comment]
@JPrause Sorry, I take the comment back... It did/does look strange in ivanchuk branch, but it will be ok when we actually release `ivanchuk-1`, so no change needed. Sorry!

**Pull request merged**
