### PR TITLE
[IVANCHUK] Backport for #1109 ([Part 3/3 of BZ#1789479] UI changes for UCI: Remove OpenStack User field from conversion host wizard, always pass "cloud-user")

### PR DESCRIPTION
**Pull request by mturley**
Ivanchuk-specific port of #1109 
Part of https://bugzilla.redhat.com/show_bug.cgi?id=1789479

Conflicts were related to https://github.com/ManageIQ/manageiq-v2v/pull/1030.

Note: this PR currently also contains the commits from #1113 , it should be rebased after that is merged before it is merged.

cc @simaishi

### CODE REVIEW

**Comment by mturley** [comment]
@simaishi I based this branch on https://github.com/ManageIQ/manageiq-v2v/pull/1113 so I could stage both before the first one is merged. Would you prefer if I close #1113 and change the title here so we just merge this to backport both #1099 and #1109 ?

**Comment by simaishi** [comment]
No, it's fine as is with 2 PRs. Just need someone to review/approve, though..

**Comment by mturley** [comment]
Yeah, I think it's past closing time for @mzazrivec .... I can ask around. @himdel would you have time to take a look at these?

**Comment by mturley** [comment]
Oh right, he's also in Brno..

**Comment by simaishi** [comment]
@mzazrivec @himdel - I'm going to merge this as I need to get the build started. But please do review as we can always rebuild if something needs to be changed.

**Comment by simaishi** [comment]
Reverted

```
commit c103746cb5c8c7df5cd7084b2cee0b3b63a3bbd5
Author: Satoe Imaishi <simaishi@redhat.com>
Date:   Mon Mar 9 13:42:20 2020 -0400

    Revert "Merge pull request #1114 from mturley/pr1109-ivanchuk-backport"

    This reverts commit d27887ee3872b6345d1a8bb3bd22d574364cc1bb, reversing
    changes made to d015f38bffe9104c9b8520bb06f9c18253b23aa1.

    https://bugzilla.redhat.com/show_bug.cgi?id=1805911
```

**Pull request merged**
