### PR TITLE
[Changelog] Initial changelog and Hammer-4 entry

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label hammer/yes

**Comment by JPrause** [comment]
@carbonin as time permits, can you review merge. We need this for today's build.

**Comment by JPrause** [comment]
Thanks @carbonin 
@mturley or @hkataria would you be able to merge. Needed for a build today.

**Comment by JPrause** [comment]
Thanks @mturley

**Comment by JPrause** [comment]
Thanks for asking @mturley 
I'll be updating it for every Sprint Review (if there are any PRs)
I'll also update for upstream releases.
ie,..it's on me to update.

**Comment by mturley** [comment]
Sounds good! Thanks for the info @JPrause

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit c69165c94532b2c6b6818ecdc00737a1c383557a
Author: Mike Turley <mike.turley@alum.cs.umass.edu>
Date:   Wed Mar 27 10:50:48 2019 -0400

    Merge pull request #919 from JPrause/hammer4_cl
    
    [Changelog] Initial changelog and Hammer-4 entry
    
    (cherry picked from commit 63d961599bea9e7789c4bf0b3f7332d976ec2a53)
```

**Pull request merged**
