### PR TITLE
[HAMMER] Fix backport of PR#871 by adding missing fixtures for providers tests

### PR DESCRIPTION
**Pull request by mturley**
In @simaishi's backport of #871 to hammer (5d8c17ae03a55c9c6316cddbd35f7cbc3cd8883c) she removed this file because that PR renamed/moved it from its previous home as overview.providers.fixtures.js, which was introduced in #834, which was not backported to hammer.

#871 moved this file to take advantage of shared fixtures between tests for OverviewReducer and the providers actions/reducers, but since the OverviewReducer tests were never on hammer, the file hadn't existed. We do need it for these new tests to work, so I've added it back here.

Part of the Conversion Hosts UI feature BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1693339

### CODE REVIEW

**Comment by mturley** [comment]
@AllenBW , @AparnaKarve , @priley86 , do any of you have a moment to review this? it's evening for @mzazrivec so I'm not sure if he'll see it, but we need it to fix build failures tonight.

**Comment by mturley** [comment]
Or @himdel, maybe you could look at it? Just trying to find someone with the permissions who has time :)

**Comment by AllenBW** [comment]
@mturley we just looking for the tests to be passing here? looks like they are, so i'm ok to merge this if thats all yah need?

**Comment by mturley** [comment]
@AllenBW that's correct! Thanks for taking a look.

**Pull request merged**
