### PR TITLE
[#563] Clickable aggregate cards on Overview

### LINKED ISSUE #563: Explore using migrations plan status cards as selection controls for the plan list/card view below

### PR DESCRIPTION
**Pull request by michaelkro**
Fixes #563 
https://bugzilla.redhat.com/show_bug.cgi?id=1640594

# Notes
- Replaces infra mappings aggregate card with archived plans card
- Removes migration select
- Clicking on a aggregate card will show the corresponding listview in the migration plans section
- The active card gets a full border

# Screens
fullscreen_10_19_18__2_51_pm

### CODE REVIEW

**Comment by mturley** [comment]
Code looks good to me!

@vconzola when you get back, maybe we can talk about design ideas to make the selected card stand out a bit better. I played around a little with background colors, and it looks nice with `pf-blue-50`:

screenshot 2018-10-18 14 46 50

Here's that same color without the full border:
screenshot 2018-10-18 14 50 18

**Comment by AparnaKarve** [comment]
@michaelkro Looks nice -- this is a great addition!

**Comment by AparnaKarve** [comment]
When I navigate to the Mappings screen from the Migration screen, and then navigate back to Migration screen, the card that I had selected previously does not get selected.

Would have been nice if the last state was remembered...but I guess it all boils down to the `react-router-dom` thing that we were trying to address in https://github.com/ManageIQ/manageiq-v2v/pull/709

**Comment by michaelkro** [comment]
PR updated with UI change.  The active card will no longer have the full blue border, but instead

1.  Background color of `$color-pf-blue-50`
2. Top accent border as was before

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 3871da83102c33504e74ad0531a9031c870fa064
Author: Aparna Karve <aparna.karve@gmail.com>
Date:   Fri Oct 19 12:02:13 2018 -0700

    Merge pull request #720 from michaelkro/563-clickable-aggregate-cards
    
    [#563] Clickable aggregate cards on Overview
    
    (cherry picked from commit 8361fac0e54d4dbf9b8aa905e1737be7bfb118c9)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1640594
```

**Pull request merged**
