### PR TITLE
[#872] QE: Fix missing bootstrap-touchspin class on settings input tag

### LINKED ISSUE #872: [QEDevCollab] Need bootstrap-touchspin class in input tag of Migration Settings
**What need to do**
We need 'bootstrap-touchspin' added in class of this input tag.

**Location**
Compute > Migration > Migration Setting

On this page, we will get three widgets  `+ button`, `- button` and `input field`. Problem is related to input field only.

 screenshot from 2019-02-04 18-13-25

**Why is it so?**
We have created Widgets from [standard patternfly design](https://www.patternfly.org/pattern-library/widgets/#bootstrap-touchspin) and current implementation doesn't follow those, so when our automation framework try to find class with "standard" `bootstrap-touchspin` it is not finding that.

**Actual** 
```
<input id="max_concurrent_tasks_per_host" value="10" class="form-control">
```

**Expected**
```
<input id="max_concurrent_tasks_per_host" value="10" class="form-control bootstrap-touchspin">
```
cc @mturley  @vconzola

### PR DESCRIPTION
**Pull request by mturley**
Fixes #872.

### CODE REVIEW

**Comment by Yadnyawalkya** [comment]
Thanks for quick help @mturley @vconzola  :+1:  :100: 
@simaishi we want this fix in every 5.10 build to run QE automation, can we have it after this merge?

**Comment by mturley** [comment]
I'm going to make a brief exception to the usual rule and merge this myself, since we're short-staffed right now and it's such a trivial change.

**Comment by Yadnyawalkya** [comment]
ACK. Thanks a lot @mturley .

**Comment by simaishi** [comment]
@Yadnyawalkya Since this isn't a change we need to let customer know about and you (=QE) are already aware of the change coming in, I'm fine without a BZ.

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit d10ca74a0c34f7e27d7968b4cb1f08ee6ba4d908
Author: Mike Turley <mike.turley@alum.cs.umass.edu>
Date:   Tue Feb 5 14:56:19 2019 -0500

    Merge pull request #873 from mturley/872-qe-bootstrap-touchspin
    
    [#872] QE: Fix missing bootstrap-touchspin class on settings input tag
    
    (cherry picked from commit a44b71235ead02912ad97c6a26737b6931c426f2)
```

**Pull request merged**
