### PR TITLE
[WIP][V2V] Move V2V-Related Models from Core to this Repo

### PR DESCRIPTION
**Pull request by jerryk55**
Move all V2V-related model code from the ManageIQ/manageiq (core) repo to manageiq-v2v.

In order to keep all V2V code in a common repo, the model code (and related spec tests) are being moved to this repo. A separate PR will remove this set of code from the core repo.

A second PR will move API code from the manageiq-api repo to this repo as well as another to remove that code from the api repo.

This PR has no dependencies.

@djberg96 @agrare @roliveri please review.

### CODE REVIEW

**Comment by jerryk55** [comment]
@miq-bot add-label hammer/no

**Comment by agrare** [comment]
Hey @jerryk55 you probably want to use git filter branch to maintain the history of these files across repos.  @juliancheal has a tool to assist with this (https://github.com/juliancheal/code-extractor)

**Comment by jerryk55** [comment]
Oh cool, thanks @agrare.  I'll look at the tool.

**Comment by mturley** [comment]
@agrare, that `code-extractor` tool looks interesting, but can it create commits to an existing repo? It looks like the use case described there is creating an entirely new repo with the extracted code. We might have to do something like this afterwards: https://saintgimp.org/2013/01/22/merging-two-git-repositories-into-one-repository-without-losing-file-history/

**Comment by agrare** [comment]
@mturley yeah you just have to merge unrelated histories afterwards, I've done this a few times on the manageiq-providers-vmware repo.

**Comment by mturley** [comment]
Nice. Seems like a really useful approach.

**Comment by mturley** [comment]
@jerryk55 after this is merged we should decide on how we'll share the newly combined issue/PR lists, I'm thinking maybe we put a `ui` label on all existing open issues and an `api` or `model` label on the new backend-related ones, or something like that. I'm not sure if you guys will want to use GitHub Projects here, but I'm thinking we'll distinguish the [existing project board](https://github.com/ManageIQ/manageiq-v2v/projects/1) as UI-only.

**Comment by jerryk55** [comment]
Yeah @agrare I tried a test run of the tool and was confused about what the results were.  I thought it would add commits to an existing repo (which is what we want).  Instead it creates an empty git tree, apparently with two branches - one with the extracted files, and one with the original repo minus the extracted files.  Not very user friendly.  I'm trying to figure out how to use this in the way we need...

**Comment by agrare** [comment]
@jerryk55 yeah you have to add the remote for the new repo, create a new branch from the master branch, and `git merge --allow-unrelated-histories` from your extracted branch.  Then push that as your PR if I remember correctly

**Comment by jerryk55** [comment]
Ok closing this PR in order to go through the steps suggested by @agrare above in a separate PR.

**Pull request closed without merging**
