### PR TITLE
[Changelog] Update for Ivanchuk Beta1

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label ivanchuk/yes

**Comment by simaishi** [comment]
@JPrause This PR is really for Beta2 and Beta1 section is missing, FYI.

**Comment by simaishi** [comment]
Ivanchuk backport details:

```
$ git log -1
commit 5add7643e6947254d860ec0656bad96cf0156977
Author: Adam Grare <agrare@redhat.com>
Date:   Wed Aug 7 08:43:31 2019 -0400

    Merge pull request #1017 from JPrause/ivanchuk_b2
    
    [Changelog] Update for Ivanchuk Beta1
    
    (cherry picked from commit 4e209eeb4366ff3f52224c3854807ad95b969e3d)
```

**Pull request merged**
