### PR TITLE
Display the Transformation mapping info in the Plan list immediately when the list loads

### PR DESCRIPTION
**Pull request by AparnaKarve**
Fixes https://github.com/ManageIQ/manageiq-v2v/issues/694

The `Loading Infrastructure Mapping info...` status shown below won't be visible in the list anymore, and the Transformation mapping name associated with the plan would be loaded right away.

screen shot 2018-10-08 at 3 10 48 pm

Depends on PR - https://github.com/ManageIQ/manageiq/pull/18070

### CODE REVIEW

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit f33d61e472d79a9ebd459125d01beaa20620f2cf
Author: Michael Ro <mikerodev@gmail.com>
Date:   Thu Oct 11 12:39:28 2018 -0400

    Merge pull request #696 from AparnaKarve/nowait_for_transformationmappingname
    
    Display the Transformation mapping info in the Plan list immediately when the list loads
    
    (cherry picked from commit 563ad4a8b1e3c49171faf3f8f6d594e6cc83e178)
```

**Comment by simaishi** [comment]
@AparnaKarve 4 out of 5 files conflict backporting to Gaprindashvili branch. Please create a separate PR.

**Comment by AparnaKarve** [comment]
@simaishi Created #784 for Gaprindashvili

**Comment by simaishi** [comment]
Backported to Gaprindashvili via https://github.com/ManageIQ/manageiq-v2v/pull/784

**Pull request merged**
