### PR TITLE
[#843] Set backdrop='static' on all modals to prevent accidentally closing them

### LINKED ISSUE #843: Modals (especially Wizards) should not automatically close when clicking the background overlay

### PR DESCRIPTION
**Pull request by mturley**
Fixes #843

### CODE REVIEW

**Comment by h-kataria** [comment]
@mturley should this be labeled as Bug?

**Comment by mturley** [comment]
I'm not sure whether we'd want to consider this a bugfix or an enhancement, @vconzola what do you think?

**Comment by vconzola** [comment]
From a PF standpoint it's definitely not a bugfix. I talked with Serena about it and the modal pattern is used in some applications as a sidebar where you want it to close by clicking off of it. In our case, I think we can argue it's a bug, but probably better just considered an enhancement. I assume this question is coming from whether or not it needs to be backported for GA? If so, then I'd say it's not a blocker bug and doesn't need to be backported. Agree?

**Comment by mturley** [comment]
That sounds reasonable to me. Not sure where the question is coming from, @h-kataria, is it a question of backporting? Marking this as an enhancement based on that assumption.

**Comment by h-kataria** [comment]
@mturley as i am preparing for the sprint demo, it helps to report the counts of Bugs/Enhancements when all PRs are labeled appropriately, and that will also help in determining whether the PR should be backported.

**Comment by mturley** [comment]
Got it. Thanks @h-kataria, I'll be sure to include those labels going forward.

**Comment by vconzola** [comment]
BZ for this issue: https://bugzilla.redhat.com/show_bug.cgi?id=1678370

**Comment by fdupont-redhat** [comment]
@vconzola @mturley should/could it be backported to hammer ?

**Comment by mturley** [comment]
@fdupont-redhat It should backport cleanly to hammer. Might be nice to have.

**Comment by fdupont-redhat** [comment]
@miq-bot add_label hammer/yes

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit 9fdb37f3ac1e86b4faaa796d61d1542b3874c058
Author: Michael Ro <mikerodev@gmail.com>
Date:   Mon Jan 7 09:46:50 2019 -0500

    Merge pull request #844 from mturley/843-modal-backdrop-static
    
    [#843] Set backdrop='static' on all modals to prevent accidentally closing them
    
    (cherry picked from commit 0a648343fd3f5fe3be1e7ec2b0f02af0a0358b67)
    
    Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1686871
```

**Pull request merged**
