### PR TITLE
[Changelog] Update for Hammer-5 release

### PR DESCRIPTION
**Pull request by JPrause**
[skip ci]

### CODE REVIEW

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
@miq-bot add_label hammer/yes

**Comment by JPrause** [comment]
@mturley as time permits, can you review/merge.

**Comment by mturley** [comment]
@JPrause, many of these changes (all of the conversion host related changes) are not visible to the user until https://github.com/ManageIQ/manageiq-v2v/pull/922 is released (which enables that feature and was merged today). With the feature disabled, the additions have no effect and the fixes are for issues that were never exposed. Should we still include them here?

**Comment by JPrause** [comment]
Hmm. Looking at that PR922,...I see it has the label hammer/yes.
Satoe should backport that PR to the hammer branch, then kick off the hammer-5 build early next week. That means it'd be available.
The upstream changelogs are added to master just before the build is done.
Satoe then cherry-picks to the upstream branch then builds.

However, it's ultimately your call about whether we merge this changelog. I can close this PR if you feel these shouldn't be exposed just yet.

**Comment by mturley** [comment]
That's fair. I imagine we need to update this changelog just before the build and include #922 as well as anything else merged before the build that isn't already listed (like https://github.com/ManageIQ/manageiq-v2v/pull/941 and https://github.com/ManageIQ/manageiq-v2v/pull/915 and https://github.com/ManageIQ/manageiq-v2v/pull/932).

Sorry we're getting so many things in so close to build time :)

**Comment by simaishi** [comment]
@JPrause `hammer/yes` doesn't mean it will be included in the next build (in this case `hammer-5`). What's included in the hammer branch now is what will be in hammer-5.

**Comment by simaishi** [comment]
@JPrause please ping me when you have updated changelog PR for hammer-5

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit d9c4d70a0b6ef9148d0e273a970930bc07d09aea
Author: Mike Turley <mike.turley@alum.cs.umass.edu>
Date:   Thu Apr 18 15:55:14 2019 -0400

    Merge pull request #939 from JPrause/hammer5_cl
    
    [Changelog] Update for Hammer-5 release
    
    (cherry picked from commit 2d61f8894a1ee455230d0ff6ffc2652893be6ee9)
```

**Pull request merged**
