### PR TITLE
Conversion Host Configuration Wizard - rename API field from ssh_key to conversion_host_ssh_private_key

### PR DESCRIPTION
**Pull request by mturley**
Corresponds to the field being renamed here: https://github.com/ManageIQ/manageiq/pull/18309/files#diff-700df9b1e35abc841c7dda6c72bd9fedR54
Also depends on the field being renamed in https://github.com/ManageIQ/manageiq/pull/18541.

### CODE REVIEW

**Comment by mzazrivec** [comment]
@mturley The change looks good, but I guess we'll have to wait for those 2 backend PRs to be merged first. Correct?

**Comment by mturley** [comment]
@mzazrivec we can, or we can just merge it since the page is still hidden. I'm fine with either way. The old `ssh_key` field that was already merged in the UI wasn't ready in the API yet anyway.

**Comment by mzazrivec** [comment]
@mturley OK, merging.

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit b8f39b73264982abffe87faeaf6ff461bc3453cc
Author: Milan Zázrivec <mzazrivec@redhat.com>
Date:   Wed Mar 20 09:56:56 2019 +0100

    Merge pull request #913 from mturley/conv-host-wizard-ssh-field-name
    
    Conversion Host Configuration Wizard - rename API field from ssh_key to conversion_host_ssh_private_key
    
    (cherry picked from commit 3e28cca810f0b6cae0164249bea0a218f93f9d0e)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1696423
```

**Pull request merged**
