### PR TITLE
[HAMMER] Update hammer gettext catalog

### PR DESCRIPTION
**Pull request by mzazrivec**
This PR contains:

* updated `.pot` catalog
* translations for the updated catalog

This must be merged with https://github.com/ManageIQ/manageiq-ui-classic/pull/5089

### CODE REVIEW

**Comment by djberg96** [comment]
Any reason not to merge this since ManageIQ/manageiq-ui-classic#5089 was merged?

**Comment by djberg96** [comment]
@mzazrivec I think it' needs a hammer/yes label.

And would Satoe would handle the actual merging/backporting?

**Comment by simaishi** [comment]
> @mzazrivec I think it' needs a hammer/yes label.

Since it's a PR against `hammer` branch, `hammer/yes` label isn't needed.
 
> And would @simaishi handle the actual merging/backporting?

I will merge once approved.

**Comment by mzazrivec** [comment]
@himdel review please? Thanks.

**Comment by mturley** [comment]
@mzazrivec is this PR still relevant? do we need to update it again or should we close it?

**Comment by mzazrivec** [comment]
I'm going to close it, since it makes no sense for it to be open without actual translations for v2v being done.

**Pull request closed without merging**
