### PR TITLE
Move v2v product features to plugin repo

### PR DESCRIPTION
**Pull request by mzazrivec**
1. v2v product features can live in the plugin repo (remove from core in https://github.com/ManageIQ/manageiq/pull/18884)
2. fix for product features structure to mimic ui / menu structure

Before
roles-before

After
roles-after

### CODE REVIEW

**Comment by djberg96** [comment]
:+1:

**Comment by mturley** [comment]
@mzazrivec I think we'll need to update this to reflect the new location of the Migration menu after https://github.com/ManageIQ/manageiq-v2v/pull/995 is merged

**Comment by mzazrivec** [comment]
> @mzazrivec I think we'll need to update this to reflect the new location of the Migration menu after #995 is merged

Yup, will do that once it's merged.

**Comment by mzazrivec** [comment]
It seems no changes will be needed here after all, since the presentation logic automatically picks up the menu structure.

This one is ready for review / good to go.

roles

**Comment by mturley** [comment]
Oh, nice. Thanks for checking that.

**Pull request merged**
