### PR TITLE
[#802] Prevent Settings form from being destroyed on unmount

### LINKED ISSUE #802: Migration Settings page goes blank, highlights wrong menu selection in Vertical Navigation
https://bugzilla.redhat.com/show_bug.cgi?id=1651403

### PR DESCRIPTION
**Pull request by mturley**
Fixes #802, which is re-exposed by #822 after having been hidden by #769.

### CODE REVIEW

**Comment by mturley** [comment]
@michaelkro, I think KK's console errors are unrelated. If I test it on Milan's branch `mzazrivec:phase_2_of_vertical_menu_fixes`, I can reproduce the issue without any console errors (navigate away from settings page and back), and then if I cherry-pick this commit on top of that branch, it is fixed again.

I would have assumed that fetching the form data on mount would fix it, too... but something funky is going on with redux-form. It seems that when the form gets destroyed on unmount, it's not fully reinitialized on a second mount.

**Comment by h-kataria** [comment]
@mturley should this be labeled as Bug?

**Comment by mturley** [comment]
Yes it should, thanks @h-kataria. Labeled.

**Comment by simaishi** [comment]
Hammer backport details:

```
$ git log -1
commit f295e552246d656a3b4e1020c0356ab58fd583db
Author: Michael Ro <mikerodev@gmail.com>
Date:   Mon Jan 7 12:31:51 2019 -0500

    Merge pull request #839 from mturley/prevent-settings-destroy
    
    [#802] Prevent Settings form from being destroyed on unmount
    
    (cherry picked from commit 4aad87810b1881ca53821bcc0e5812d6bf0d6848)
    
    https://bugzilla.redhat.com/show_bug.cgi?id=1693743
```

**Pull request merged**
